### ISSUE TITLE
Manage Team Member View Bug

### ISSUE THREAD

**Issue by joshuajames-smith** [gliff-ai/manage#215]
## Describe the bug

My staging account plan is the lowest. 
As I login, I now only see the projects board on MANAGE. If I move into CURATE and then back into MANAGE suddenly I am able to go onto team members and collaborators. 

## To Reproduce

Steps to reproduce the behaviour:

1.  Go to staging.gliff.app
2.  Login to account
3.  View MANAGE and only see project board
4.  Navigate into CURATE
5.  Navigate back into MANAGE
6.  View MANAGE and now see project, team members and collaborators board
7.  See error?

## Expected behaviour

I would expect consistent viewing of MANAGE without new areas unlocking after engaging with the app. I should either see projects board ONLY or all boards. But not both.

## Screenshots

<img width="1791" alt="Screenshot 2021-11-23 at 13 01 12" src="https://user-images.githubusercontent.com/83074763/143029321-0e890bbc-c8e8-40ff-b90a-7ac555bb54a7.png">
<img width="1792" alt="Screenshot 2021-11-23 at 13 02 05" src="https://user-images.githubusercontent.com/83074763/143029328-bcf18db2-4009-4a7a-8f00-280e9814f838.png">

## System Info (please complete the following information):

- OS: macOS Monterey
- Browser: safari and google chrome
- Browser version: v15.1 and v95.0.4638.69 (Official Build) (x86_64)

## Additional context

I believe my staging account is the lowest but am I then actually a team owner by default? How should this type of account view MANAGE? Assuming this error likely affects team member or collaborator accounts?

**Comment by cooper667** [comment]
`I believe my staging account is the lowest but am I then actually a team owner by default? `

yea, so you can't add people (but you can add collabs) and you SHOULD be able to see those tabs

**Comment by SilviaZeta** [comment]
I am closing this issue, because it was fixed by https://github.com/gliff-ai/manage/pull/208
